# Generated by Django 4.2.2 on 2023-06-18 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('NUMERO_CLIENTE', models.AutoField(primary_key=True, serialize=False)),
                ('NOMBRE_Y_APELLIDO', models.CharField(max_length=120)),
                ('DIRECCION', models.CharField(max_length=255)),
                ('EMAIL', models.CharField(blank=True, max_length=120, null=True)),
                ('TELEFONO', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='gastosAdicionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRODUCTO', models.CharField(max_length=255, unique=True)),
                ('IMPORTE', models.DecimalField(decimal_places=2, default=1, max_digits=22)),
            ],
        ),
        migrations.CreateModel(
            name='gastosFijos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DETALLE', models.CharField(max_length=255)),
                ('TOTAL', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'verbose_name': 'Gasto fijo',
                'verbose_name_plural': 'Gastos fijos',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRODUCTO', models.CharField(max_length=120, unique=True)),
                ('DETALLE', models.TextField(blank=True, null=True)),
                ('STOCK', models.IntegerField(blank=True, default=0, null=True)),
                ('CANTIDAD', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('UNIDAD_MEDIDA_COMPRA', models.CharField(choices=[('Unidades', 'Unidades'), ('Kilogramos', 'Kilogramos'), ('Litros', 'Litros'), ('Onzas', 'Onzas'), ('Libras', 'Libras')], default='Unidades', max_length=10)),
                ('PRECIO_COMPRA', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('UNIDAD_MEDIDA_USO', models.CharField(choices=[('Unidades', 'Unidades'), ('Gramos', 'Gramos'), ('Mililitros', 'Mililitros'), ('Onzas', 'Onzas'), ('Libras', 'Libras')], default='Unidades', max_length=10)),
                ('COSTO_UNITARIO', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMPRESA', models.CharField(max_length=120)),
                ('NOMBRE', models.CharField(max_length=120)),
                ('DIRECCION', models.CharField(blank=True, max_length=120, null=True)),
                ('EMAIL', models.EmailField(blank=True, max_length=254, null=True)),
                ('TELEFONO', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('CODIGO', models.AutoField(primary_key=True, serialize=False)),
                ('ESTADO', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Entregado', 'Entregado')], default='Pendiente', max_length=20)),
                ('FECHA_ENTREGA', models.DateField(blank=True, null=True)),
                ('NOMBRE', models.CharField(max_length=120, verbose_name='PRODUCTO')),
                ('DETALLE', models.TextField(blank=True, null=True)),
                ('DIAS_DE_TRABAJO', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('RENTABILIDAD', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('PRECIO_VENTA', models.DecimalField(decimal_places=2, default=1, max_digits=22)),
                ('COSTO_FINAL', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=22, null=True)),
                ('VALIDO_HASTA', models.DateField(blank=True, null=True)),
                ('ULTIMA_ACTUALIZACION', models.DateTimeField(auto_now=True, null=True)),
                ('ARTICULOS', models.TextField(blank=True, null=True)),
                ('GASTOS_ADICIONALES', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=22, null=True, verbose_name='TOTAL ADICIONALES')),
                ('ADICIONALES', models.ManyToManyField(blank=True, to='administracion.gastosadicionales')),
                ('CLIENTE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.cliente')),
                ('INGREDIENTES', models.ManyToManyField(to='administracion.insumo')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
            },
        ),
        migrations.CreateModel(
            name='PedidosEntregados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODIGO', models.CharField(max_length=10)),
                ('FECHA_ENTREGA', models.DateField(blank=True, null=True)),
                ('ARTICULO', models.TextField()),
                ('DETALLE', models.CharField(blank=True, max_length=120, null=True)),
                ('DIAS_DE_TRABAJO', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('COSTO_RECETA', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=22, null=True, verbose_name='Costo articulos')),
                ('MANO_DE_OBRA', models.DecimalField(decimal_places=2, default=1, max_digits=22)),
                ('PRECIO', models.DecimalField(decimal_places=2, default=1, max_digits=22)),
                ('INGREDIENTES', models.TextField(blank=True, null=True)),
                ('GASTOS_ADICIONALES', models.TextField(blank=True, null=True)),
                ('CLIENTE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='insumo',
            name='PROVEEDOR',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.proveedor'),
        ),
        migrations.CreateModel(
            name='ingredientereceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('medida_uso', models.CharField(blank=True, max_length=255, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.insumo')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.receta')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos incluidos en presupuesto',
            },
        ),
        migrations.AddField(
            model_name='gastosadicionales',
            name='RECETA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.receta'),
        ),
        migrations.CreateModel(
            name='GastoAdicionalReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costoTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Costo total')),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.gastosadicionales')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.receta')),
            ],
        ),
    ]
