# Generated by Django 4.2.2 on 2023-06-18 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GastoAdicionalReceta',
        ),
    ]
