# Generated by Django 4.2.2 on 2023-06-18 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_delete_gastoadicionalreceta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastosadicionales',
            name='IMPORTE',
        ),
        migrations.RemoveField(
            model_name='gastosadicionales',
            name='RECETA',
        ),
        migrations.CreateModel(
            name='adicionalreceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('adicional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.gastosadicionales')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.receta')),
            ],
        ),
    ]
