# Generated by Django 4.2.2 on 2023-06-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_remove_gastosadicionales_importe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidosentregados',
            name='GASTOS_ADICIONALES',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=22, null=True, verbose_name='TOTAL ADICIONALES'),
        ),
    ]
