# Generated by Django 4.2.2 on 2023-06-18 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_alter_pedidosentregados_gastos_adicionales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidosentregados',
            name='FECHA_ENTREGA',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
