# Generated by Django 4.2.2 on 2023-06-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_alter_pedidosentregados_fecha_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='FECHA_ENTREGA',
            field=models.DateField(null=True),
        ),
    ]
